export const mockConversations = [
  {
    id: "1",
    name: "Alice Reyes",
    lastMessage: "Hey! Are you free later?",
    time: "10:42 AM",
    unread: 3,
    online: true,
    avatar: "AR",
  },
  {
    id: "2",
    name: "Juan dela Cruz",
    lastMessage: "Got it, thanks!",
    time: "Yesterday",
    unread: 0,
    online: false,
    avatar: "JD",
  },
  {
    id: "3",
    name: "Dev Team 🚀",
    lastMessage: "Carlo: Push na ba?",
    time: "Yesterday",
    unread: 5,
    online: false,
    avatar: "DT",
  },
  {
    id: "4",
    name: "Maria Santos",
    lastMessage: "Sige see you tomorrow!",
    time: "Mon",
    unread: 0,
    online: true,
    avatar: "MS",
  },
  {
    id: "5",
    name: "Jose Rizal",
    lastMessage: "Noli me tangere 📖",
    time: "Sun",
    unread: 1,
    online: false,
    avatar: "JR",
  },
];
